name: My Finances - Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    
    - name: list all
      run: ls -a
        
    - name: Build with Maven
      run: 
        cd tree/main/backend
        mvn -B package --file pom.xml
      
    - name: Tests with Junit
      run: 
        cd tree/main/backend
        mvn test
